env:
  SET_VERSION_OVERRIDE: 1.5-hubspot-SNAPSHOT
  MAVEN_ARGS: -Dmaven.gitcommitid.skip=true -am -pl protoc-bundled-plugin

buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: Blazar-Buildpack-Java
  branch: v2-single-module

